name: M365 User Report

on:
  push:
    branches:
      - main

jobs:
  report:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Microsoft Graph
        shell: pwsh
        run: |
          Install-Module Microsoft.Graph -Scope CurrentUser -Force

      - name: Run Script
        shell: pwsh
        run: |
          ./scripts/Get-M365Users.ps1

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: M365Users
          path: users.csv