name: M365 User Report

on:
  push:
    branches:
      - main

jobs:
  validate:

      runs-on: ubuntu-latest

      steps:

        - uses: actions/checkout@v4

        - name: Install PSScriptAnalyzer
          shell: pwsh
          run: |
            Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

        - name: Analyze Scripts
          shell: pwsh
          run: |
            Invoke-ScriptAnalyzer -Path ./scripts -Recurse
        - name: Install Pester
          shell: pwsh
          run: |
            Install-Module Pester -Force -Scope CurrentUser

        - name: Run Tests
          shell: pwsh
          run: |
            Invoke-Pester ./tests

  report:
      runs-on: ubuntu-latest

      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      steps:
        - uses: actions/checkout@v4

        - name: Install Microsoft Graph
          shell: pwsh
          run: |
            Install-Module Microsoft.Graph -Scope CurrentUser -Force

        - name: Run Script
          shell: pwsh
          run: |
            ./scripts/Get-M365Users.ps1

        - name: Upload CSV
          uses: actions/upload-artifact@v4
          with:
            name: M365Users
            path: users.csv