name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-powershell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run PowerShell script
        shell: pwsh
        run: |
          Write-Host "CI Pipeline is running"
          Get-Date
          Write-Host "Hello from GitHub Actions"